- src/components/doctors/You.js
Changement de https://www.vyte.in/ecosante/rendez-vous-medecin à https://www.vyte.in/recosante/rendez-vous-medecin
> Modifie l'URL de prise de RDV qui était obsolète

- content/texts/mentions-legales.md
Est-ce que tu veux bien relire pour vérifier que je n'ai pas écris de bétises ?
> Modifie mentions légales

- src/components/layout/Section.js
- src/components/stats/AllUsers.js
- src/components/stats/CurrentMonth.js
- src/components/stats/Profile.js
- src/pages/stats.js
J’ai fait des changements sur les stats suite à des discussions avec @annepoirot 
@florianpanchout Je ne suis pas très à l’aise avec le JS du coup je veux bien une rieview de ce que j’ai fait.
Normalement ça donne quelque chose comme la capture qui suit
> Nouvelle page stats

- src/html.js
Update script and add the recording feature !
> add recording

- content/texts/form.json
- content/texts/inscription-patients.md
- src/components/home/landing/SubscribeForm.js
- src/components/profile/formWrapper/form/Title.js
@annepoirot je te laisse revoir la formulation.
> On ne demande plus d’informations sensibles

- content/pages/pollens/ambroisies.md
- content/pages/pollens/armoises.md
- content/pages/pollens/aulne.md
- content/pages/pollens/bouleau.md
- content/pages/pollens/charme.md
- content/pages/pollens/chataignier.md
- content/pages/pollens/chene.md
- content/pages/pollens/cupressacees.md
- content/pages/pollens/frene.md
- content/pages/pollens/graminees.md
- content/pages/pollens/noisetier.md
- content/pages/pollens/olivier.md
- content/pages/pollens/peuplier.md
- content/pages/pollens/plantain.md
- content/pages/pollens/platane.md
- content/pages/pollens/rumex.md
- content/pages/pollens/saule.md
- content/pages/pollens/tilleul.md
- content/pages/pollens/urticacees.md
- src/components/dashboard/indicators/raep/details/Element.js
- src/components/modals/WrapperModal.js
> Définition des 19 pollens

- src/utils/recommandationsSteps.js
En lien avec cette PR backend : https://github.com/betagouv/recosante-api/pull/378
> Modification des textes pour recommandations enfants et chauffage

- src/components/Search.js
- src/components/subscription/Identity.js
> En savoir plus sur la gestion des données personnelles

- src/utils/formatPlaceUrl.js
Validé sur la liste complète actuelle des 35 049 communes françaises
> Slug des communes avec plusieurs caractères spéciaux

- content/pages/donnees-personnelles.md
- src/components/Search.js
- src/components/layout/footer/Links.js
- src/components/subscription/Identity.js
- Titre "Politique de Confidentialité" devient "Gestion des données personnelles"
- URL https://recosante.beta.gouv.fr/donnees-personnelles
> Modification de la page sur les données personnelles

- src/components/layout/header/MobileSearch.js
> Boutons superposés sur le widget

- src/components/dashboard/indicators/IndiceAtmo.js
- src/components/dashboard/indicators/IndiceUv.js
- src/components/dashboard/indicators/Raep.js
- src/components/dashboard/indicators/VigilanceMeteo.js
> Adaptation des textes pour les libellés géo

- content/pages/baignades.md
- content/pages/indiceatmo.md
- content/pages/indiceuv.md
- content/pages/potentielradon.md
- content/pages/raep.md
- content/pages/vigilancemeteo.md
- content/texts/data.md
- content/texts/partenaires.md
- content/texts/recommandations.md
- gatsby-node.js
- src/components/Recommandations.js
- src/components/layout/footer/Links.js
- src/hooks/useRecommandations.js
- src/templates/recommandations.js
Il sera accessible sur le site (lien depuis le footer et depuis les infobulles des indicateurs) et téléchargeable au format CSV avec une entête. En image...
NB : certaines recommandations sont très contextuelles donc moins compréhensibles sans les critères qui les déterminent
> Mise en ligne du catalogue des recommandations

- src/components/Dashboard.js
- src/components/dashboard/EpisodePollution.js
- src/components/dashboard/Header.js
- src/components/dashboard/Indicators.js
- src/components/dashboard/header/EpisodePollution.js
- src/components/dashboard/indicators/IndiceAtmo.js
- src/components/dashboard/indicators/IndiceUv.js
- src/components/dashboard/indicators/Raep.js
- src/components/dashboard/indicators/VigilanceMeteo.js
- src/components/dashboard/indicators/indiceUv/Chart.js
- src/hooks/useIndicators.js
> Affichage des indicateurs du lendemain

- src/components/base/FancySelect.js
- src/components/dashboard/Header.js
- Nouvel événement : Search > DateChange
- Valeurs de la liste déroulante précédemment invisible sur Firefox, Edge et Chrome Windows
> Tracking du changement de date et fix du sélecteur

- content/pages/suppressioncompte.md
- src/components/modals/DeleteModal.js
- src/components/subscription/profile/Delete.js
- src/components/subscription/profile/InactiveProfile.js
> Revue du processus de désinscription depuis les préférences

- content/texts/newsletter-modal.md
> Lien vers les dernières éditions lors de l'inscription

- content/texts/recommandations.md
- src/components/Recommandations.js
7 types :
- Épisode de pollution
- Qualité de l’air
- Risque d’allergie aux pollens
- Vigilance météo
- Indice UV
- Qualité des eaux de baignade
- Potentiel Radon
Des critères propres à chaque type documentés ici : https://pad.incubateur.net/vpGaiEa0R5GZ_3xNIqh8rQ
> Filtrage des recommandations par type et critères principaux

- src/components/Dashboard.js
- src/components/dashboard/Header.js
> Basculement rapide entre aujourd'hui et demain

- src/components/dashboard/indicators/vigilanceMeteo/Details.js
- src/components/dashboard/indicators/vigilanceMeteo/details/Element.js
Les différentes vigilances (rouge, orange, jaune) des phénomènes sont détaillés ainsi que les créneaux horaires durant lesquels ils ont lieu.
Avant :
> Ajout des créneaux horaires des phénomènes
